version: "3.7"

services:
  postgres:
    image: postgres:16
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=dbname
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
volumes:
  pgdata:
