version: "3.7"

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb10.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=UTC
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
